run_test_line echo1.test
run_test_line list_of_true_false.test
run_test_file indecisive_true.test 
run_test_file indecisive_false.test 
#run_test_file fuck_malloc1.test
#run_test_file fuck_malloc2.test
run_test_line simple_exit.test
run_test_line complex_exit.test
run_test_file ascii_house.test
run_test_line simple_cd.test
