run_test_line echo1.test
run_test_line list_of_true_false.test
run_test_file indecisive_true.test 
run_test_file indecisive_false.test 
run_test_file fuck_malloc1.test
run_test_file fuck_malloc2.test
