run_test_line redir_DGREAT.test
run_test_line redir_DIVERS.test
run_test_line redir_GREATAND.test
run_test_line redir_GREAT.test
run_test_line redir_LESSAND.test
run_test_line redir_LESSGREAT.test
run_test_line redir_LESS.test
run_test_line redir_SHELL_COMMAND.test
