run_test_file simple_unalias.test
run_test_file bad_unalias.test
run_test_file bad_unalias_no_arg.test
run_test_file unalias_list.test
run_test_file unalias_all.test
run_test_file complex_alias.test
run_test_file alias_mult_word_sub.test
run_test_file alias_function_def.test
