run_test_file question_mark_1.test
run_test_file question_mark_2.test
run_test_file question_mark_3.test
run_test_file echo_when_first.test
run_test_file question_mark_neg.test
run_test_file question_and_or.test
run_test_file question_pipe.test
run_test_file question_redir.test
