run_test_file basic.test
run_test_file nested_block.test
run_test_file no_rbrace.test
run_test_file no_lbrace.test
run_test_file no_space1.test
run_test_file no_space2.test
run_test_line error_in_compound_list.test
